#!/usr/bin/env bash
set -euo pipefail

# Delete inbox files that have one or more (name+size) matches in media
# Generated: Tue Dec 23 07:33:53 PST 2025
# Root constraint: only deletes files under:
#   /Users/tedshaffer/Pictures/ShafferographyInbox

LOCAL_ROOT="/Users/tedshaffer/Pictures/ShafferographyInbox"

safe_rm() {
  local p="$1"
  # Must exist
  [ -e "$p" ] || { echo "SKIP (missing): $p"; return 0; }
  # Must be under LOCAL_ROOT
  case "$p" in
    "$LOCAL_ROOT"/*) ;;
    *) echo "SKIP (outside LOCAL_ROOT): $p"; return 0 ;;
  esac
    rm -v -- "$p"
}

echo "Starting deletes... (interactive rm -i)"

safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2703.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2538.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2736\ 2.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2492.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2884.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2754.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2611.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2892.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2742.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2607.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2596.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2715.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2914.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2447.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2502.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_6111.heic
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2851.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2781.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2410.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2806.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2555.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2739.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2693.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2369.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2406.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2543.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2810.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2685.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2451.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2902.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2847.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2514.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2797.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2778.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2563.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2830.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2426.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2758.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2867.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2534.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2922.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2888.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2522.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2488.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2871.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2719.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2826.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2575.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2762.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2918.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2670.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2735.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2559.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2723.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2689.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2774.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2518.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2519.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2775.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2667.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2722.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2688.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2558.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2671.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2734.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2919.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2763.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2827.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2574.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2431.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2718.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2523.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2489.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2870.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2866.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2535.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2923.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2889.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2759.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2562.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2831.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2427.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2779.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2450.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2903.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2846.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2515.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2684.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2407.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2542.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2811.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2387.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2692.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2368.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2411.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2807.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2554.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2780.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2915.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2503.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2850.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2714.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2651.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2597.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2743.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2606.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2485.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2893.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2755.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2610.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2539.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2493.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2885.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2702.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2709.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2836.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2565.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2420.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2498.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2532.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2861.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2924.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2748.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2877.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2524.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2898.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2573.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2820.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2621.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2764.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2508.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2676.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2699.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2733.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2725.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2549.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2772.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2908.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2569.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2586.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2705.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2640.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2494.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2882.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2928.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2752.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2617.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2528.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_6091.heic
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2894.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2744.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2601.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2590.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2713.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2656.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2441.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2912.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2857.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2504.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2787.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2768.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2416.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2553.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2695.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2400.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2816.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2545.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2683.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2729.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2904.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2512.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2841.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2791.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2790.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2905.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2513.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2840.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2397.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2682.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2728.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2544.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2694.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2417.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2552.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2786.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2769.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2913.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2856.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2505.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2712.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2657.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2591.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2745.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2600.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2529.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2895.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2753.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2616.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2495.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2883.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2929.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2704.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2641.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2568.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2587.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2909.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2773.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2548.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2724.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2677.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2698.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2732.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2509.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2620.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2765.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2572.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2821.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2437.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2876.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2525.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2899.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2749.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2499.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2533.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2860.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2925.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2837.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2564.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2421.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2708.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2770.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2727.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2398.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2418.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2731.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2674.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2859.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2766.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2789.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2434.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2822.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2571.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2658.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2930.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2526.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2875.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2926.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2530.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2619.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2422.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2588.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2567.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2834.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2639.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2793.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2843.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2510.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2906.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2681.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2394.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2547.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2814.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2402.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2697.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2382.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2678.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2551.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2414.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2785.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2506.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2855.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2910.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2443.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2654.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2711.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2438.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2592.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2603.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2746.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2896.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2879.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2615.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2750.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2880.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2496.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2642.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2707.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2838.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2585.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2839.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2643.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2706.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2881.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2497.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2614.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2751.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2897.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2878.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2602.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2747.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2439.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2593.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2655.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2710.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2507.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2854.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2911.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2784.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2550.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2696.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2679.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2546.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2815.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2403.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2680.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2395.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2842.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2511.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2907.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2638.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2792.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2589.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2566.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2835.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2618.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2927.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2862.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2531.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2931.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2527.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2874.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2823.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2570.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2767.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2622.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2788.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2858.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2730.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2675.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2419.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2726.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2819.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2771.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2795.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2516.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2845.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2900.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2453.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2687.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2668.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2812.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2541.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2404.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2691.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2384.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2557.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2783.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2853.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2500.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2916.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2652.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2717.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2594.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2828.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2605.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2740.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2890.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2486.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2613.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2756.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2886.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2869.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2490.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2644.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2701.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2428.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2849.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2776.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2799.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2408.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2721.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2371.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2808.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2388.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2672.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2449.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2760.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2598.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2873.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2520.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2609.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2920.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2536.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2865.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2424.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2832.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2561.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2425.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2833.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2560.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2921.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2537.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2864.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2608.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2872.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2521.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2599.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2825.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2761.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2673.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2809.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2720.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2370.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2409.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2777.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2798.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2848.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2429.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2700.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2887.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2868.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2491.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2612.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2757.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2891.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2487.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2604.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2741.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2595.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2829.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2653.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2716.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2852.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2501.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2444.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2917.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2782.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2556.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2805.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2690.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2813.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2540.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2405.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2686.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2393.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2669.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2517.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2844.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2901.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2452.HEIC
safe_rm /Users/tedshaffer/Pictures/ShafferographyInbox/IMG_2794.HEIC

echo "Done."
